#include 'protheus.ch'
#include 'totvs.ch'


/*/{Protheus.doc} zTGroup
Construir uma tela com TGroup
@type user function
@author Gabriel Viana
@since 03/05/2024
@version 1.0
@see (links_or_references)
https://tdn.totvs.com/display/tec/TGroup
/*/
User Function zTGroup()

	local oDlg

	local cGet1, oGet1
    local cGet2, oGet2
    local cGet3, oGet3
    local cGet4, oGet4

	local oButton1, oButton2

	local oGroup1, oGroup2

	oDlg := TDialog():New(0,0,410,410,'Elemento Tgroup com TGet',,,,,CLR_RED,CLR_WHITE,,,.T.)

	//Grupo 1
	oGroup1:= TGroup():New(010,010,100,200,'Grupo 1',oDlg,,,.T.)

	//TGet1
	cGet1 := Space(20)
	oGet1 := TGet():New(30,30,{|u|if(PCount()==0,cGet1,cGet1:=u)},oGroup1,100,10,"@",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,,)

	//TGet2
	cGet2 := Space(20)
	oGet2 := TGet():New(50,30,{|u|if(PCount()==0,cGet2,cGet2:=u)},oGroup1,100,10,"@",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet2,,,,)

	//TButton
	oButton1 := TButton():New(70, 30, "Ok", oGroup1, {||}, 60,15,,,.F.,.T.,.F.,,.F.,,,.F. )

    //------------------------------------------------------------------

	//Grupo 2
	oGroup2 := TGroup():New(110,010,200,200,'Grupo 2',oDlg,,,.T.)

	//TGet3
	cGet3 := Space(20)
	oGet3 := TGet():New(130,30,{|u|if(PCount()==0,cGet3,cGet3:=u)},oGroup2,100,10,"@",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet3,,,,)

	//TGet4
	cGet4 := Space(20)
	oGet4 := TGet():New(150,30,{|u|if(PCount()==0,cGet4,cGet4:=u)},oGroup2,100,10,"@",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet4,,,,)

	//TButton2
	oButton2 := TButton():New(170, 30, "Sair", oGroup2, {||}, 60,15,,,.F.,.T.,.F.,,.F.,,,.F. )


	oDlg:activate(,,,.T.)



Return
